package fr.oreo.modernClaims.api.gui;

public enum ModernClaimsMenu {
    CLAIM_MAIN,
    CLAIM_INFO,
    CLAIM_MEMBERS,
    CLAIM_ROLE_EDITOR,
    CLAIM_FLAG_EDITOR,
    CLAIM_TRANSFER,
    CLAIM_RENT_SELL,
    CLAIM_UPGRADES,
    CLAIM_MAP_BROWSER,
    CLAIM_SEARCH,
    TOWN_MAIN,
    TOWN_MEMBERS,
    TOWN_RANKS,
    TOWN_FLAGS,
    TOWN_BANK,
    TOWN_UPGRADES,
    NATION_MAIN,
    NATION_MEMBERS,
    NATION_DIPLOMACY,
    NATION_FLAGS,
    NATION_BANK,
    ADMIN_MAIN,
    AUDIT_LOGS,
    CLAIM_MODERATION,
    INACTIVITY_BROWSER
}
